name: fragmentation
networks:
  main:
    name: unified-net
    external: true

services:
  fragmentation:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fragmentation
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./uploads:/app/uploads
    networks:
      - main
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fragmentation.rule=Host(`frag-dev.4lb.ca`)"
      - "traefik.http.routers.fragmentation.entrypoints=websecure"
      - "traefik.http.routers.fragmentation.tls.certresolver=letsencrypt"
      - "traefik.http.routers.fragmentation.middlewares=crowdsec@file,geoblock@file,security-headers@file"
      - "traefik.http.services.fragmentation.loadbalancer.server.port=3000"
